# Generated by Django 5.1.1 on 2024-09-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
