# Generated by Django 5.1.1 on 2024-09-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Alert', '0003_remove_profile_email_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_job_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote')], max_length=10),
        ),
    ]
