# Generated by Django 5.1.1 on 2024-09-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Alert', '0005_profile_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_job_title',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('analyst', 'Analyst')], max_length=100),
        ),
    ]
