# Generated by Django 5.1.1 on 2024-09-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Alert', '0007_alter_profile_preferred_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link_to_original_source',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='india', max_length=100),
        ),
    ]
