# Generated by Django 5.1.1 on 2024-09-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Alert', '0008_alter_job_link_to_original_source_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(max_length=400),
        ),
    ]
