# Generated by Django 5.1.1 on 2024-09-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Alert', '0006_alter_profile_preferred_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_job_title',
            field=models.CharField(choices=[('django/python developer', 'Django/Python Developer'), ('ui ux designer', 'UI UX Designer'), ('project manager', 'Project Manager'), ('full stack web developer', 'Full Stack Web Developer'), ('mern stack developer', 'MERN Stack Developer'), ('artificial intelligence(ai) and machine learning(ml) engineer', 'AI/ML Engineer'), ('data scientist/analyst', 'Data Scientist/Analyst')], max_length=100),
        ),
    ]
